### ISSUE TITLE
License: attribution

### ISSUE THREAD

**Issue by satsen** [networkspore/Netnotes-Linux#3]
Hi, this repository contains code from Satergo. Satergo is licensed under the Apache 2.0 license which requires attribution. Can you add attribution somewhere that links to the Satergo code and specifies that it is Apache 2.0 (for example: Includes code from [Satergo](https://github.com/Satergo/Satergo), licensed under Apache 2.0), either in the readme or a new file or whatever you think is appropriate so that that criterion of the license is fulfilled. Perhaps it is enough to have the attribution as a comment in the relevant files or in the root of the satergo code directory, I don't know much about it.

**Comment by networkspore** [comment]
Yeah I don't know much about it either, but I've updated the main readme with a section for credits. Thanks
